### ISSUE TITLE
Shift + D to toggle Dark Mode

### ISSUE THREAD

**Issue by duttakapil** [coderplex-org/coderplex-org#1]
We can use the `Shift + D` command to toggle the dark mode on the website. Shift because Ctrl most likely will be pre-set to some different action, eg : bookmarking the current page in the browser, and would be easier to set for both Windows and Mac systems

**Comment by appsplash99** [comment]
Hey,
I am currently learning react and hence i thought of giving it a try.

*Please correct me if i my approach is wrong:*
I am currently thinking to solve this problem is via including a useEffect hook which will track the keyDown of 'shift+D',
and all this must be updated within the [toggle.tsx file](https://github.com/coderplex-org/coderplex-org/blob/edc879f72ed7197e499205c1eb431674a3afa8a8/src/components/ui/toggle/Toggle.tsx)

Am i going correct?

**Comment by pbteja1998** [comment]
Yes, that approach will work. If you want to work on this, please remember to raise the PR to `beta` branch instead of `master`.

**Comment by duttakapil** [comment]
Maybe we should update this issue to add other keyboard shortcuts as well, for example, when a dialogue box is open, like the Donate or See who liked, pressing `Esc` should close them as well. There might be other possible shortcuts we can add like this

**Comment by pbteja1998** [comment]
@duttakapil we can add those shortcuts to `v0. 3`. Let's just keep this issue as it is.

**Comment by appsplash99** [comment]
Can you assign it to me?
